version: "3.9"

volumes:
  db_data:
    driver: local

services:
  web:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
    env_file:
      - .env
    volumes:
      - ./app:/code
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
    - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5