apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: app
        image: rolandoramos/todo-app:1.0
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "app.settings"
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-host
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-port
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000